import sys, os

sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))

from Functions.Converter import TimestampToDatetime


class DayData:
    def __init__(self, data, source = 'DB'):
        self.datetime = TimestampToDatetime(data['timestamp'])
        self.timestamp = data['timestamp']
        self.azimuth = data['azimuth']
        self.elevation = data['elevation']
        self.lux = data['lux']
        self.cct = data['cct']
        self.swR100 = data['swR100']
        self.mwR100 = data['mwR100']
        self.lwR100 = data['lwR100']
        self.x1931 = data['x1931']
        self.y1931 = data['y1931']
        self.u1960 = data['u1960']
        self.v1960 = data['v1960']
        self.u1976 = data['u1976']
        self.v1976 = data['v1976']
        self.deltaUV = data['deltaUV']



        if source == 'DB':
            # self.azimuth = data['az']
            # self.elevation = data['el']

            self.cri = data['cri']
            self.r1 = data['r1']
            self.r2 = data['r2']
            self.r3 = data['r3']
            self.r4 = data['r4']
            self.r5 = data['r5']
            self.r6 = data['r6']
            self.r7 = data['r7']
            self.r8 = data['r8']
            self.r9 = data['r9']
            self.r10 = data['r10']
            self.r11 = data['r11']
            self.r12 = data['r12']
            self.r13 = data['r13']
            self.r14 = data['r14']
            self.spd = data['spd']
            self.intgtime = data['intgtime']

            # 위성 데이터
            self.gkb01_kc = data['gkb01_kc']
            self.gkb02_kc = data['gkb02_kc']
            self.gkb03_kc = data['gkb03_kc']
            self.gkb04_kc = data['gkb04_kc']
            self.gkb05_kc = data['gkb05_kc']
            self.gkb06_kc = data['gkb06_kc']
            self.gkb07_kc = data['gkb07_kc']
            self.gkb08_kc = data['gkb08_kc']
            self.gkb09_kc = data['gkb09_kc']
            self.gkb10_kc = data['gkb10_kc']
            self.gkb11_kc = data['gkb11_kc']
            self.gkb12_kc = data['gkb12_kc']
            self.gkb13_kc = data['gkb13_kc']
            self.gkb14_kc = data['gkb14_kc']
            self.gkb15_kc = data['gkb15_kc']
            self.gkb16_kc = data['gkb16_kc']
            self.gkct = ['gkct']
            self.gkcot_kc = ['gkcot_kc']
            self.gkcer_kc = ['gkcer_kc']

            self.gkb01_sl = data['gkb01_sl']
            self.gkb02_sl = data['gkb02_sl']
            self.gkb03_sl = data['gkb03_sl']
            self.gkb04_sl = data['gkb04_sl']
            self.gkb05_sl = data['gkb05_sl']
            self.gkb06_sl = data['gkb06_sl']
            self.gkb07_sl = data['gkb07_sl']
            self.gkb08_sl = data['gkb08_sl']
            self.gkb09_sl = data['gkb09_sl']
            self.gkb10_sl = data['gkb10_sl']
            self.gkb11_sl = data['gkb11_sl']
            self.gkb12_sl = data['gkb12_sl']
            self.gkb13_sl = data['gkb13_sl']
            self.gkb14_sl = data['gkb14_sl']
            self.gkb15_sl = data['gkb15_sl']
            self.gkb16_sl = data['gkb16_sl']

            self.gkb01_line = data['gkb01_line']
            self.gkb02_line = data['gkb02_line']
            self.gkb03_line = data['gkb03_line']
            self.gkb04_line = data['gkb04_line']
            self.gkb05_line = data['gkb05_line']
            self.gkb06_line = data['gkb06_line']
            self.gkb07_line = data['gkb07_line']
            self.gkb08_line = data['gkb08_line']
            self.gkb09_line = data['gkb09_line']
            self.gkb10_line = data['gkb10_line']
            self.gkb11_line = data['gkb11_line']
            self.gkb12_line = data['gkb12_line']
            self.gkb13_line = data['gkb13_line']
            self.gkb14_line = data['gkb14_line']
            self.gkb15_line = data['gkb15_line']
            self.gkb16_line = data['gkb16_line']

            self.gkb01_arr = data['gkb01_arr']
            self.gkb02_arr = data['gkb02_arr']
            self.gkb03_arr = data['gkb03_arr']
            self.gkb04_arr = data['gkb04_arr']
            self.gkb05_arr = data['gkb05_arr']
            self.gkb06_arr = data['gkb06_arr']
            self.gkb07_arr = data['gkb07_arr']
            self.gkb08_arr = data['gkb08_arr']
            self.gkb09_arr = data['gkb09_arr']
            self.gkb10_arr = data['gkb10_arr']
            self.gkb11_arr = data['gkb11_arr']
            self.gkb12_arr = data['gkb12_arr']
            self.gkb13_arr = data['gkb13_arr']
            self.gkb14_arr = data['gkb14_arr']
            self.gkb15_arr = data['gkb15_arr']
            self.gkb16_arr = data['gkb16_arr']

        elif source == 'Platform':

            self.cri = data['crI_Ra']
            self.r1 = data['crI_R'][0]
            self.r2 = data['crI_R'][1]
            self.r3 = data['crI_R'][2]
            self.r4 = data['crI_R'][3]
            self.r5 = data['crI_R'][4]
            self.r6 = data['crI_R'][5]
            self.r7 = data['crI_R'][6]
            self.r8 = data['crI_R'][7]
            self.r9 = data['crI_R'][8]
            self.r10 = data['crI_R'][9]
            self.r11 = data['crI_R'][10]
            self.r12 = data['crI_R'][11]
            self.r13 = data['crI_R'][12]
            self.r14 = data['crI_R'][13]

            self.spd = {}
            self.intgtime = 0

            # 위성 데이터
            self.gkb01_kc = data['gkB01_KC']
            self.gkb02_kc = data['gkB02_KC']
            self.gkb03_kc = data['gkB03_KC']
            self.gkb04_kc = data['gkB04_KC']
            self.gkb05_kc = data['gkB05_KC']
            self.gkb06_kc = data['gkB06_KC']
            self.gkb07_kc = data['gkB07_KC']
            self.gkb08_kc = data['gkB08_KC']
            self.gkb09_kc = data['gkB09_KC']
            self.gkb10_kc = data['gkB10_KC']
            self.gkb11_kc = data['gkB11_KC']
            self.gkb12_kc = data['gkB12_KC']
            self.gkb13_kc = data['gkB13_KC']
            self.gkb14_kc = data['gkB14_KC']
            self.gkb15_kc = data['gkB15_KC']
            self.gkb16_kc = data['gkB16_KC']
            self.gkct = ['gkCT']
            self.gkcot_kc = ['gkCOT_KC']
            self.gkcer_kc = ['gkCER_KC']

            self.gkB01_SL = data['gkB01_SL']
            self.gkB02_SL = data['gkB02_SL']
            self.gkB03_SL = data['gkB03_SL']
            self.gkB04_SL = data['gkB04_SL']
            self.gkB05_SL = data['gkB05_SL']
            self.gkB06_SL = data['gkB06_SL']
            self.gkB07_SL = data['gkB07_SL']
            self.gkB08_SL = data['gkB08_SL']
            self.gkB09_SL = data['gkB09_SL']
            self.gkB10_SL = data['gkB10_SL']
            self.gkB11_SL = data['gkB11_SL']
            self.gkB12_SL = data['gkB12_SL']
            self.gkB13_SL = data['gkB13_SL']
            self.gkB14_SL = data['gkB14_SL']
            self.gkB15_SL = data['gkB15_SL']
            self.gkB16_SL = data['gkB16_SL']

            self.gkB01_LINE = data['gkB01_LINE']
            self.gkB02_LINE = data['gkB02_LINE']
            self.gkB03_LINE = data['gkB03_LINE']
            self.gkB04_LINE = data['gkB04_LINE']
            self.gkB05_LINE = data['gkB05_LINE']
            self.gkB06_LINE = data['gkB06_LINE']
            self.gkB07_LINE = data['gkB07_LINE']
            self.gkB08_LINE = data['gkB08_LINE']
            self.gkB09_LINE = data['gkB09_LINE']
            self.gkB10_LINE = data['gkB10_LINE']
            self.gkB11_LINE = data['gkB11_LINE']
            self.gkB12_LINE = data['gkB12_LINE']
            self.gkB13_LINE = data['gkB13_LINE']
            self.gkB14_LINE = data['gkB14_LINE']
            self.gkB15_LINE = data['gkB15_LINE']
            self.gkB16_LINE = data['gkB16_LINE']

            self.gkB01_ARR = data['gkB01_ARR']
            self.gkB02_ARR = data['gkB02_ARR']
            self.gkB03_ARR = data['gkB03_ARR']
            self.gkB04_ARR = data['gkB04_ARR']
            self.gkB05_ARR = data['gkB05_ARR']
            self.gkB06_ARR = data['gkB06_ARR']
            self.gkB07_ARR = data['gkB07_ARR']
            self.gkB08_ARR = data['gkB08_ARR']
            self.gkB09_ARR = data['gkB09_ARR']
            self.gkB10_ARR = data['gkB10_ARR']
            self.gkB11_ARR = data['gkB11_ARR']
            self.gkB12_ARR = data['gkB12_ARR']
            self.gkB13_ARR = data['gkB13_ARR']
            self.gkB14_ARR = data['gkB14_ARR']
            self.gkB15_ARR = data['gkB15_ARR']
            self.gkB16_ARR = data['gkB16_ARR']


    def setSPD(self, spds, wavelength=[str(w) for w in range(380, 781)]):
        if type(spds) is dict:
            self.spd = spds
        else:
            self.spd = {wl: spd for wl, spd in zip(wavelength, spds)}

    def setIntgrationTime(self, intgtime):
        self.intgtime = intgtime
